spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/carrental"
    username: house
    password: 30052545
  jpa:
    show_sql: true
    hibernate: 
      ddl-auto: update
  jackson:
    deserialization:
      fail-on-unknown-properties: true
